version: '3.8'

services:
  creaturesncaves:
    build: .
    image: cnc:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      NODE_ENV: development
      REACT_APP_SERVER_ADDRESS: http://localhost:80
      ConnectionStrings__DBConnectionString: "Host=172.18.0.1;Port=5432;Username=cnc_admin;Password=xxxx;Database=cnc;"
    ports:
      - "8080:80"

  database:
    image: postgres:latest
    container_name: psql-cnc
    environment:
      - POSTGRES_PASSWORD=xxxx
    volumes:
      - ./EntityFramework/Database/Scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
      - ./persisted:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
