version: '3'

services:
  creaturesncaves:
    image: cnc:latest
    container_name: cnc-app
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      NODE_ENV: production
      REACT_APP_SERVER_ADDRESS: http://localhost:80
    ports:
      - "8080:80"

  database:
    image: postgres:latest
    container_name: psql-cnc
    environment:
      - POSTGRES_PASSWORD=xxxx
    volumes:
      - ${HOME}/db/cnc/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ${HOME}/db/cnc/persisted:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
