// <auto-generated />
using EntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CreaturesNCaves.Server.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("EntityFramework.Models.Campaign", b =>
                {
                    b.Property<string>("CampaignId")
                        .HasColumnName("campaign_id")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("character varying(1024)")
                        .HasMaxLength(1024);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnName("user_id")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("CampaignId")
                        .HasName("campaign_id");

                    b.HasIndex("UserId")
                        .HasName("ix_campaigns_user_id");

                    b.ToTable("campaigns");
                });

            modelBuilder.Entity("EntityFramework.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("character varying(1024)")
                        .HasMaxLength(1024);

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnName("hashed_password")
                        .HasColumnType("character(128)")
                        .IsFixedLength(true)
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnName("username")
                        .HasColumnType("character varying(32)")
                        .HasMaxLength(32);

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.ToTable("users");

                    b.HasComment("Collection of users");
                });

            modelBuilder.Entity("EntityFramework.Models.Campaign", b =>
                {
                    b.HasOne("EntityFramework.Models.User", "User")
                        .WithMany("Campaigns")
                        .HasForeignKey("UserId")
                        .HasConstraintName("campaigns_user_id_fkey")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
